### ISSUE TITLE
Getting Error!

### ISSUE THREAD

**Issue by Xeek3y** [Geeky-cat/go-karona#1]
Hello i'm trying to use this script but i'm getting error while running the script, at first it worked fine but it sometimes stops/became idle after extracting few domains, like when i executed this command:
`python go-karona.py *.edmodo.com`
And also when i try to stop the script after few subdomains(it becomes idle after extracting few subdomains as i said above) with `CRTL+C` it is generating the html file with 0bytes which is of no use :/
But now even after running above command it is not working anymore and just throwing this error:
```
Traceback (most recent call last):
  File "go-karona.py", line 120, in <module>
    urls = waybackurls(host)
  File "go-karona.py", line 15, in waybackurls
    r = requests.get(url,headers=headers)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine('No status line received - the server has closed the connection',))
```

**Comment by Geeky-cat** [comment]
The program looks idle after extracting few domains is due to large number of sorting going in background.I'll fix it soon with better algorithm and get you updated. Do you also want an option to stop it after enumerating some assets?

**Comment by Xeek3y** [comment]
> 
> 
> The program looks idle after extracting few domains is due to large number of sorting going in background.I'll fix it soon with better algorithm and get you updated. Do you also want an option to stop it after enumerating some assets?

Yeah aight please fix asap because this is a good tool :)
yeah if i wanted to terminate or stop the script then it should stop :/

**Comment by Geeky-cat** [comment]
Fixed those issues, can you verify it?
